version: "3.8"

name: code-arena-dev

networks:
  backend:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: code-arena-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=CODE_ARENA
      - TZ=Asia/Seoul

    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./data/mysql-files:/var/lib/mysql-files
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1